import { CountryCode, CountryInfo } from '@/types/open-api';

export const COUNTRIES: Map<CountryCode, CountryInfo> = new Map<
  CountryCode,
  CountryInfo
>([
  [
    CountryCode.BH,
    {
      countryCode: CountryCode.BH,
      countryName: 'Bahrain',
      cities: [
        'Manama',
        'Riffa',
        'Muharraq',
        'Isa Town',
        'Hamad Town',
        'Sitra',
        'Budaiya',
      ],
      currency: 'BHD',
    },
  ],
  [
    CountryCode.EG,
    {
      countryCode: CountryCode.EG,
      countryName: 'Egypt',
      cities: [
        'Cairo',
        'Alexandria',
        'Giza',
        'Sharm El Sheikh',
        'Hurghada',
        'Luxor',
        'Aswan',
        'Mansoura',
        'Tanta',
      ],
      currency: 'EGP',
    },
  ],
  [
    CountryCode.IQ,
    {
      countryCode: CountryCode.IQ,
      countryName: 'Iraq',
      cities: [
        'Baghdad',
        'Basra',
        'Erbil',
        'Mosul',
        'Najaf',
        'Karbala',
        'Sulaymaniyah',
        'Kirkuk',
      ],
      currency: 'IQD',
    },
  ],
  [
    CountryCode.JO,
    {
      countryCode: CountryCode.JO,
      countryName: 'Jordan',
      cities: [
        'Amman',
        'Irbid',
        'Zarqa',
        'Mafraq',
        'Ajloun',
        'Jerash',
        'Madaba',
        'Balqa',
        'Karak',
        'Tafilah',
        'Ma\'an',
        'Aqaba',
      ],
      currency: 'JOD',
    },
  ],
  [
    CountryCode.KW,
    {
      countryCode: CountryCode.KW,
      countryName: 'Kuwait',
      cities: [
        'Kuwait City',
        'Hawalli',
        'Salmiya',
        'Ahmadi',
        'Farwaniya',
        'Jahra',
        'Mangaf',
        'Sabah Al Salem',
        'Fahaheel',
        'Rumaithiya',
      ],
      currency: 'KWD',
    },
  ],
  [
    CountryCode.LB,
    {
      countryCode: CountryCode.LB,
      countryName: 'Lebanon',
      cities: [
        'Beirut',
        'Tripoli',
        'Sidon',
        'Tyre',
        'Jounieh',
        'Byblos',
        'Zahle',
      ],
      currency: 'LBP',
    },
  ],
  [
    CountryCode.OM,
    {
      countryCode: CountryCode.OM,
      countryName: 'Oman',
      cities: ['Muscat', 'Salalah', 'Sohar', 'Nizwa', 'Sur', 'Ibri', 'Buraimi'],
      currency: 'OMR',
    },
  ],
  [
    CountryCode.PS,
    {
      countryCode: CountryCode.PS,
      countryName: 'Palestine',
      cities: [
        'Gaza',
        'Ramallah',
        'Nablus',
        'Hebron',
        'Jenin',
        'Tulkarm',
        'Qalqilya',
        'Jericho',
        'Bethlehem',
        'Rafah',
      ],
      currency: 'ILS',
    },
  ],
  [
    CountryCode.QA,
    {
      countryCode: CountryCode.QA,
      countryName: 'Qatar',
      cities: [
        'Doha',
        'Al Rayyan',
        'Al Wakra',
        'Al Khor',
        'Umm Salal',
        'Al Daayen',
        'Al Shamal',
        'Al Shahaniya',
      ],
      currency: 'QAR',
    },
  ],
  [
    CountryCode.SA,
    {
      countryCode: CountryCode.SA,
      countryName: 'Saudi Arabia',
      cities: [
        'Riyadh',
        'Makkah',
        'Madinah',
        'Eastern Province',
        'Asir',
        'Tabuk',
        'Hail',
        'Northern Borders',
        'Jizan',
        'Najran',
        'Al Bahah',
        'Al Jawf',
        'Qassim',
      ],
      currency: 'SAR',
    },
  ],
  [
    CountryCode.SY,
    {
      countryCode: CountryCode.SY,
      countryName: 'Syria',
      cities: [
        'Damascus',
        'Aleppo',
        'Homs',
        'Latakia',
        'Hama',
        'Deir ez-Zor',
        'Raqqa',
        'Idlib',
        'Tartus',
        'Daraa',
      ],
      currency: 'SYP',
    },
  ],
  [
    CountryCode.AE,
    {
      countryCode: CountryCode.AE,
      countryName: 'United Arabs of Emirates',
      cities: [
        'Abu Dhabi',
        'Dubai',
        'Sharjah',
        'Ajman',
        'Umm Al Quwain',
        'Ras Al Khaimah',
        'Fujairah',
      ],
      currency: 'AED',
    },
  ],
  [
    CountryCode.YE,
    {
      countryCode: CountryCode.YE,
      countryName: 'Yemen',
      cities: [
        'Sanaa',
        'Aden',
        'Taiz',
        'Hodeidah',
        'Mukalla',
        'Ibb',
        'Dhamar',
        'Amran',
        'Sayoun',
      ],
      currency: 'YER',
    },
  ],
  [
    CountryCode.SD,
    {
      countryCode: CountryCode.SD,
      countryName: 'Sudan',
      cities: [
        'Khartoum',
        'Omdurman',
        'Khartoum North',
        'Port Sudan',
        'Kassala',
        'El Obeid',
        'Wad Madani',
        'Atbara',
        'Gedaref',
      ],
      currency: 'SDG',
    },
  ],
]);
