import { CountryCode, CountryInfo } from '@/types/open-api';

export const COUNTRIES: Map<CountryCode, CountryInfo> = new Map<
  CountryCode,
  CountryInfo
>([
  [
    CountryCode.BH,
    {
      countryCode: CountryCode.BH,
      countryName: 'Bahrain',
      cities: [
        'Manama',
        'Riffa',
        'Muharraq',
        'Isa Town',
        'Hamad Town',
        'Sitra',
        'Budaiya',
      ],
      currency: 'BHD',
    },
  ],
  [
    CountryCode.EG,
    {
      countryCode: CountryCode.EG,
      countryName: 'Egypt',
      cities: [
        'Cairo',
        'Alexandria',
        'Giza',
        'Sharm El Sheikh',
        'Hurghada',
        'Luxor',
        'Aswan',
        'Mansoura',
        'Tanta',
      ],
      currency: 'EGP',
    },
  ],
  [
    CountryCode.IQ,
    {
      countryCode: CountryCode.IQ,
      countryName: 'Iraq',
      cities: [
        'Baghdad',
        'Basra',
        'Erbil',
        'Mosul',
        'Najaf',
        'Karbala',
        'Sulaymaniyah',
        'Kirkuk',
      ],
      currency: 'IQD',
    },
  ],
  [
    CountryCode.JO,
    {
      countryCode: CountryCode.JO,
      countryName: 'Jordan',
      cities: [
        'amman',
        'irbid',
        'zarqa',
        'mafraq',
        'ajloun',
        'jerash',
        'madaba',
        'balqa',
        'karak',
        'tafilah',
        'ma\'an',
        'aqaba',
      ],
      currency: 'JOD',
    },
  ],
  [
    CountryCode.KW,
    {
      countryCode: CountryCode.KW,
      countryName: 'Kuwait',
      cities: [
        'Kuwait City',
        'Hawalli',
        'Salmiya',
        'Ahmadi',
        'Farwaniya',
        'Jahra',
        'Mangaf',
        'Sabah Al Salem',
        'Fahaheel',
        'Rumaithiya',
      ],
      currency: 'KWD',
    },
  ],
  [
    CountryCode.LB,
    {
      countryCode: CountryCode.LB,
      countryName: 'Lebanon',
      cities: [
        'Beirut',
        'Tripoli',
        'Sidon',
        'Tyre',
        'Jounieh',
        'Byblos',
        'Zahle',
      ],
      currency: 'LBP',
    },
  ],
  [
    CountryCode.OM,
    {
      countryCode: CountryCode.OM,
      countryName: 'Oman',
      cities: ['Muscat', 'Salalah', 'Sohar', 'Nizwa', 'Sur', 'Ibri', 'Buraimi'],
      currency: 'OMR',
    },
  ],
  [
    CountryCode.PS,
    {
      countryCode: CountryCode.PS,
      countryName: 'Palestine',
      cities: [
        'Gaza',
        'Ramallah',
        'Nablus',
        'Hebron',
        'Jenin',
        'Tulkarm',
        'Qalqilya',
        'Jericho',
        'Bethlehem',
        'Rafah',
      ],
      currency: 'ILS',
    },
  ],
  [
    CountryCode.QA,
    {
      countryCode: CountryCode.QA,
      countryName: 'Qatar',
      cities: [
        'doha',
        'al rayyan',
        'al wakra',
        'al khor',
        'umm salal',
        'al daayen',
        'al shamal',
        'al shahaniya',
      ],
      currency: 'QAR',
    },
  ],
  [
    CountryCode.SA,
    {
      countryCode: CountryCode.SA,
      countryName: 'Saudi Arabia',
      cities: [
        'riyadh',
        'makkah',
        'madinah',
        'eastern province',
        'asir',
        'tabuk',
        'hail',
        'northern borders',
        'jizan',
        'najran',
        'al bahah',
        'al jawf',
        'qassim',
      ],
      currency: 'SAR',
    },
  ],
  [
    CountryCode.SY,
    {
      countryCode: CountryCode.SY,
      countryName: 'Syria',
      cities: [
        'Damascus',
        'Aleppo',
        'Homs',
        'Latakia',
        'Hama',
        'Deir ez-Zor',
        'Raqqa',
        'Idlib',
        'Tartus',
        'Daraa',
      ],
      currency: 'SYP',
    },
  ],
  [
    CountryCode.AE,
    {
      countryCode: CountryCode.AE,
      countryName: 'United Arabs of Emirates',
      cities: [
        'abu dhabi',
        'dubai',
        'sharjah',
        'ajman',
        'umm al quwain',
        'ras al khaimah',
        'fujairah',
      ],
      currency: 'AED',
    },
  ],
  [
    CountryCode.YE,
    {
      countryCode: CountryCode.YE,
      countryName: 'Yemen',
      cities: [
        'Sanaa',
        'Aden',
        'Taiz',
        'Hodeidah',
        'Mukalla',
        'Ibb',
        'Dhamar',
        'Amran',
        'Sayoun',
      ],
      currency: 'YER',
    },
  ],
  [
    CountryCode.SD,
    {
      countryCode: CountryCode.SD,
      countryName: 'Sudan',
      cities: [
        'Khartoum',
        'Omdurman',
        'Khartoum North',
        'Port Sudan',
        'Kassala',
        'El Obeid',
        'Wad Madani',
        'Atbara',
        'Gedaref',
      ],
      currency: 'SDG',
    },
  ],
]);
